### ISSUE TITLE
Setup basic django framework

### ISSUE THREAD

**Issue by fireballpoint1** [OSDG-IIITH/art-club-website#4]
Involves setting up a Django framework with appropriate make files and documentation on using the same.

**Comment by pscyk** [comment]
Can i get assigned on this issue
thanks

**Comment by pscyk** [comment]
The previous pr has been updated
should i keep the bin/ and lib/ (virtual env stuff) outside the src/ or keep everything related inside src/

**Comment by fireballpoint1** [comment]
inside src

**Comment by pscyk** [comment]
updated

**Comment by pscyk** [comment]
I have added the missing files
Had to do
```bash
 git add -f .
``` 
 for them (donno why git add . didnt work)
